site_name: Kube
pages:
- Index: index.md
- Project: project.md
- Design: design.md
- Requirements: requirements.md
- Cryptography: cryptography.md
- Dev environment setup: setting-up-dev-env.md
theme: readthedocs
