find_path(GPGME_INCLUDE_DIR NAMES gpgme.h)
find_library(GPGME_LIBRARIES NAMES gpgme)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GPGME DEFAULT_MSG GPGME_INCLUDE_DIR GPGME_LIBRARIES)
